### ISSUE TITLE
V kompaktním zobrazení chybí v TJČ mezera za zkratkou slovního druhu

### ISSUE THREAD

**Issue by daliboris** [lsd-cz/feedback#2]
### Postup

- v Tezauru českého jazyka zobrazím libovolné heslo
- nastavím zobrazení na kompaktní

### Výsledek

Mezi zkratkou slovního druhu a prvním výrazem chybí mezera.

![sb-zvíře](https://user-images.githubusercontent.com/8056045/211409742-3758ffbb-b63e-467f-884f-36c0c33e3525.png)

### Poznámka

V CSS je pravidlo definováno následovně, tj. bez dodané mezery:

```css
.Mode--Compact .EntryArticle ul li:first-child:after, .Mode--Compact .EntryArticle ul li:last-child:after {
    content: "";
}
```
